// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/26/2025, 8:31:11 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/junny/project-test/frontband/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/plugins/**/*.{js,ts,mjs}","/Users/junny/project-test/frontband/composables/**/*.{js,ts,mjs}","/Users/junny/project-test/frontband/utils/**/*.{js,ts,mjs}","/Users/junny/project-test/frontband/pages/index.vue","/Users/junny/project-test/frontband/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/junny/project-test/frontband/app.config.{js,ts,mjs}","/Users/junny/project-test/frontband/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;